### ISSUE TITLE
Auth with GitHub

### ISSUE THREAD

**Issue by spoenemann** [theia-ide/extension-registry#1]
The registry currently features basic login functionality with a hard-coded dummy user. We should use an OAuth service. It would be great to set up a dummy OAuth implementation in Gitpod so we can test the login.

**Comment by AlexTugarev** [comment]
> It would be great to set up a dummy OAuth implementation in Gitpod so we can test the login.

I tried that, it was too tedious. There is nothing running OOTB.

> We should use an OAuth service.

Going to add GitHub OAuth.

**Comment by AlexTugarev** [comment]
'will try to integrate with https://quarkus.io/guides/security-oauth2

edit: there seems to be nothing we can just reuse. the whole web flow story (FE and BE) is to be implemented from scratch.

this is an example how to add basic auth with quarkus: https://quarkus.io/guides/security#form-based-authentication

**Comment by spoenemann** [comment]
In progress on https://github.com/eclipse/openvsx
